#!/usr/bin/env sh
# Orchestrates the disposable real-server fixture: the production dashboard and
# guard from compose.yaml plus a real Paper server, on a distinct Compose project
# with disposable volumes and secrets generated here.
# Usage: scripts/integration.sh up | down
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
env_file="$root/runtime/integration.env"

compose() {
	docker compose --env-file "$env_file" \
		-f "$root/compose.yaml" -f "$root/compose.integration.yaml" "$@"
}

# Test-only secrets, never committed and never printed. runtime/ is gitignored.
generate_env() {
	umask 077
	mkdir -p "$root/runtime"
	{
		echo "# Generated by scripts/integration.sh. Disposable, test-only, never commit."
		echo "BLOCKOPS_RCON_PASSWORD=$(openssl rand -hex 24)"
		echo "BLOCKOPS_ENCRYPTION_KEY=$(openssl rand -base64 32)"
		echo "BLOCKOPS_MINECRAFT_CONTAINER=blockops-integration-minecraft"
		echo "BLOCKOPS_PUBLIC_ORIGIN=http://127.0.0.1:${BLOCKOPS_PORT:-8099}"
		echo "BLOCKOPS_PORT=${BLOCKOPS_PORT:-8099}"
		echo "BLOCKOPS_GAME_PORT=${BLOCKOPS_GAME_PORT:-25566}"
		echo "BLOCKOPS_COOKIE_SECURE=false"
		# compose.yaml requires this to interpolate; compose.integration.yaml
		# mounts the same project-scoped volume over the same target.
		echo "MINECRAFT_DATA_SOURCE=minecraft-data"
	} >"$env_file"
}

# Diagnostics must not leak the generated secrets into a terminal or a CI log.
redact() {
	sed -e "s|$(secret BLOCKOPS_RCON_PASSWORD)|[redacted-rcon-password]|g" \
		-e "s|$(secret BLOCKOPS_ENCRYPTION_KEY)|[redacted-encryption-key]|g"
}

secret() {
	sed -n "s|^$1=||p" "$env_file"
}

case "${1:-}" in
up)
	[ -f "$env_file" ] || generate_env
	"$root/scripts/compose-assert.sh" --env-file "$env_file" \
		-f "$root/compose.yaml" -f "$root/compose.integration.yaml"
	compose build --quiet
	# --wait blocks on all three health checks, so Minecraft's mc-health probe is
	# the ready signal. A first boot also downloads the pinned Paper version.
	if ! compose up --detach --wait --wait-timeout 900; then
		compose ps --all 2>&1 | redact
		compose logs --no-color --tail 200 2>&1 | redact
		echo 'integration fixture failed to become healthy; run scripts/integration.sh down' >&2
		exit 1
	fi
	printf 'integration fixture ready: dashboard on http://127.0.0.1:%s\n' "$(secret BLOCKOPS_PORT)"
	;;
down)
	# Compose still needs the required variables to interpolate, so a missing
	# file gets throwaway values that this branch deletes again.
	[ -f "$env_file" ] || generate_env
	compose down --volumes --remove-orphans
	rm -f "$env_file"
	printf 'integration fixture removed: project blockops-integration, volumes included\n'
	;;
*)
	echo 'usage: scripts/integration.sh up | down' >&2
	exit 2
	;;
esac
